### ISSUE TITLE
Add the translations

### ISSUE THREAD

**Issue by xpmn** [2brew/2brew.github.io#2]
I need help to translate the app to another languages. If you fluent in any foreign language, please add the translation here:
https://github.com/2brew/2brew.github.io/blob/master/src/translation/i18n.json

**Comment by tdserapio** [comment]
May I add indentions?

**Comment by tdserapio** [comment]
Please assign this to me

**Comment by xpmn** [comment]
@tdserapio Hi, just create a PR and I'll approve it if everything is ok, this issue will be closed in one or two days

**Comment by tdserapio** [comment]
@rewkha If I am not mistaken, my title of PR is 'Update i18n.json', which I have added the Filipino language.

**Comment by shngt** [comment]
Hi, mind if I add Hindi?

**Comment by xpmn** [comment]
Thanks for everyone
